In [2]:
import numpy as np
import math

S = exp(bk)/sum(l, exp(bl)) for all k

In [8]:
def softmax(x):
    shift = x - np.max(x)
    exps = np.exp(shift)
    return exps / np.sum(exps)

In [3]:
vector = [1,2,3]

In [4]:
np.exp(vector)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [5]:
sum(np.exp(vector))

30.19287485057736

In [6]:
np.exp(vector)/sum(np.exp(vector))

array([0.09003057, 0.24472847, 0.66524096])

In [7]:
softmax(vector)

array([0.09003057, 0.24472847, 0.66524096])

In [9]:
vector = [6, 10, 20]

In [10]:
np.exp(vector)/sum(np.exp(vector))

array([8.31490278e-07, 4.53978310e-05, 9.99953771e-01])

In [11]:
softmax(vector)

array([8.31490278e-07, 4.53978310e-05, 9.99953771e-01])

In [1]:
def cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    	Note that y is not one-hot encoded vector. 
    	It can be computed as y.argmax(axis=1) from one-hot encoded vectors of labels if required.
    """
    m = y.shape[0]
    p = softmax(X)
    # We use multidimensional array indexing to extract 
    # softmax probability of the correct label for each sample.
    # Refer to https://docs.scipy.org/doc/numpy/user/basics.indexing.html#indexing-multi-dimensional-arrays for understanding multidimensional array indexing.
    log_likelihood = -np.log(p[range(m),y])
    loss = np.sum(log_likelihood) / m
    return loss

In [2]:
def delta_cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    	Note that y is not one-hot encoded vector. 
    	It can be computed as y.argmax(axis=1) from one-hot encoded vectors of labels if required.
    """
    m = y.shape[0]
    grad = softmax(X)
    grad[range(m),y] -= 1
    grad = grad/m
    return grad